import {
  faCheckDouble,
  faRightFromBracket,
  faMessage,
  faSquarePlus,
  faThumbTack,
  faCommentDots,
  faUserGroup,
  faCheck,
  faXmark,
  faPaperclip,
  faPaperPlane,
  faSuitcase,
  faGear,
  faBookmark,
  faCalendar,
  faFolder,
  faMagnifyingGlass,
  faMicrophone,
  faInfo,
  faUserPlus,
} from "@fortawesome/free-solid-svg-icons";

export const Icons = {
  checkDouble: faCheckDouble,
  rightFromBracket: faRightFromBracket,
  message: faMessage,
  squarePlus: faSquarePlus,
  thumbtack: faThumbTack,
  commentDots: faCommentDots,
  userGroup: faUserGroup,
  check: faCheck,
  xMark: faXmark,
  paperclip: faPaperclip,
  paperPlane: faPaperPlane,
  suitcase: faSuitcase,
  gear: faGear,
  bookmark: faBookmark,
  calendar: faCalendar,
  folder: faFolder,
  magnifyingGlass: faMagnifyingGlass,
  microphone: faMicrophone,
  info: faInfo,
  userPlus: faUserPlus,
};
