import type { Metadata } from "next";
import { Manrope, Poppins } from "next/font/google";
import "@/styles/globals.css";

import { cn } from "@/lib/utils";
import UserProvider from "@/lib/providers/user";
import AuthProvider from "@/lib/providers/auth";
import QueryProvider from "@/lib/providers/query";

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Chat application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          manrope.variable
        )}
      >
        <UserProvider>
          <QueryProvider>
            <AuthProvider>{children}</AuthProvider>
          </QueryProvider>
        </UserProvider>
      </body>
    </html>
  );
}
